repos:
  - repo: https://github.com/python/black.git
    rev: 22.10.0
    hooks:
      - id: black
        files: '\.py$'
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - pep8-naming
        entry: flake8
        files: '\.py$'
  - repo: https://github.com/pycqa/isort.git
    rev: 5.6.4
    hooks:
      - id: isort
        files: '\.py$'
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        files: '\.py$'
        args: ["--py39-plus"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.982"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        files: '\.py$'
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.5.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
