name: Continuous Integration
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install node 14.x
        uses: actions/setup-node@v2
        with:
          node-version-file: 'frontend/.nvmrc'
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            frontend/node_modules
          # yamllint disable rule:line-length
          key: node-${{ hashFiles('.nvmrc', 'package-lock.json', 'frontend/package-lock.json') }}
          # yamllint enable
      - name: Install node components
        run: |
          npm run gen-api-code
          npm install
          npm --prefix frontend install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt -r backend/src/gen/requirements.txt
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: format
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: black --all-files
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: isort
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: isort --all-files
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: lint
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: flake8 --all-files
      - name: lint-pep585-compliant
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: upgrade-type-hints --all-files
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: lint
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: markdownlint-cli2 --all-files
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: yamllint --all-files
