name: "Python API Client Release"

on:
  push:
    branches: [main, "feat/test"]
    paths:
      [
        "openapi/openapi.yaml",
        ".github/workflows/py-client-release.yml",
        "openapi/python_client_urllib3_templates/*",
      ]

jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: "extract openapi version"
        id: extract_version
        run: |
          version=$(sed -n "s/^  version: \"\(.*\)\"$/\1/p" openapi/openapi.yaml)
          echo "::set-output name=version::$version"

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y default-jre
          pip install wheel
      - name: Generate Python Client
        run: |
          wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.4.0/openapi-generator-cli-5.4.0.jar -O openapi-generator-cli.jar
          java -jar openapi-generator-cli.jar generate -i openapi/openapi.yaml -g python -o python_client -t "openapi/python_client_urllib3_templates" "--additional-properties=packageName=explainaboard_api_client,packageVersion=${{ steps.extract_version.outputs.version }}"
      - name: "build"
        run: |
          cd python_client
          python setup.py bdist_wheel

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.extract_version.outputs.version }}"
          title: "Python API Client"
          prerelease: true
          files: |
            python_client/dist/*.whl
